name: Build and Deploy to Cloud Run

on:
  workflow_dispatch: {} # Trigger the workflow manually

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - id: 'auth'
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v2'
        with:
          project_id: "bt-pp-dsc-y3gy"

      - name: Configure Docker
        run: |
          gcloud auth configure-docker europe-west3-docker.pkg.dev

      - name: Get Image Name
        id: image
        run: |
          IMAGE=europe-west3-docker.pkg.dev/bt-pp-dsc-y3gy/ml-ops-demo/demo_app
          TAG=$(git rev-parse --short HEAD)
          echo "::set-output name=IMAGE::$IMAGE:$TAG"

      - name: Build Docker image
        run: |
          IMAGE=${{ steps.image.outputs.IMAGE }}
          docker build -t $IMAGE ./app

      - name: Push Docker image to GCP Artifact Registry
        run: |
          IMAGE=${{ steps.image.outputs.IMAGE }}
          docker push $IMAGE

      - name: Deploy to Cloud Run
        run: |
          IMAGE=${{ steps.image.outputs.IMAGE }}
          gcloud run deploy demo-app \
            --image $IMAGE \
            --region europe-west1
